name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: install pybtex and update markdown files.
      run: |
        conda install pytest
        conda install -c conda-forge pybtex
        cd markdown_generator
        python pubsFromBib.py

    - name: git add & commit
      run: |
        # 此处可以键入邮箱及姓名
        git config --global user.email "you@example.com"
        git config --global user.name "Your Named"
        git add -A
        git commit -m "update md files"
        git push -u origin master
